steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'hello-world', '.']
  dir: 'cloudcode/hello-world/src'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--name', 'hello-world-test', '--network', 'cloudbuild', '-p', '5000', '-d', 'hello-world']
- name: 'qnib/pytest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install -r requirements.txt
    cd cloudcode/hello-world/tests
    pytest -s ./
  env:
      - 'E2E_URL=http://hello-world-test:5000'